name: Unittest xcube-clms

on:
  release:
    types: [ published ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout xcube-clms
        uses: actions/checkout@v4

      - name: Set up MicroMamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

      - name: Checkout xcube
        uses: actions/checkout@v4
        with:
          repository: xcube-dev/xcube
          path: xcube

      - name: Install and Test
        shell: bash -l {0}
        run: |
          cd xcube
          python -m pip install -e . --no-deps
          cd ..
          pytest test/ --cov=xcube_clms --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}


  PyPi-Deploy:
    name: Publish Python Package to PyPI
    runs-on: ubuntu-latest
    needs: unittest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: chartlets.py/dist
          verbose: true