name: Unittest xcube-clms

on:
  push:
  release:
    types: [ published ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout xcube-clms
        uses: actions/checkout@v4

      - name: Set up MicroMamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

      - name: Checkout xcube
        uses: actions/checkout@v4
        with:
          repository: xcube-dev/xcube
          path: xcube

      - name: Install xcube from repo
        run: |
          cd xcube
          pip install -e . --no-deps

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          pytest --cov=xcube_clms --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
