name: Unittest xcube-clms

on:
  push:
  release:
    types: [ published ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]

    steps:
      - name: checkout xcube-clms
        uses: actions/checkout@v4

      - name: Set up MicroMamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Linting with ruff
        shell: bash -l {0}
        run:
          ruff check xcube_clms test

      - name: Install and Test
        shell: bash -l {0}
        run:
          pytest test/ --cov=xcube_clms --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
