name: Unittest xcube-clms

on:
  push:
  release:
    types: [ published ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout xcube-clms
        uses: actions/checkout@v4

      - name: Create modified environment file
        shell: bash -l {0}
        run: |
          grep -v "^  - xcube" environment.yml > env_no_xcube.yml
          echo "Generated env file without xcube:"
          cat env_no_xcube.yml

      - name: Set up MicroMamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: env_no_xcube.yml

      - name: Checkout xcube
        uses: actions/checkout@v4
        with:
          repository: xcube-dev/xcube
          path: xcube

      - name: Install xcube from repo
        run: |
          cd xcube
          pip install -e . --no-deps
          echo "All installed packages:"
          pip list

      - name: Debug imports
        shell: bash -l {0}
        run: |
          echo "Current directory:"
          pwd
          echo "Python path:"
          python -c "import sys; print('\n'.join(sys.path))"
          echo "Try importing both packages:"
          python -c "import xcube; import xcube_clms; print(f'xcube: {xcube.__file__}\nxcube_clms: {xcube_clms.__file__}')"

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          pwd
          ls
          cd /home/runner/work/xcube-clms/xcube-clms
          pwd
          ls
          pytest test/ --cov=xcube_clms --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
